# Datasource & H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  
  jpa: 
    hibernate: 
      ddl-auto: create-drop
      
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver

security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      
    resource:
      userInfoUri: https://graph.facebook.com/me